global:
  evaluation_interval: 1s
  scrape_interval: 1s
  external_labels:
    monitor: 'node'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090'] ## IP Address of the localhost. Match the port to your container port
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100'] ## IP Address of the localhost