version: '3.9'
# x-default-logging: &logging
#   driver: "json-file"
#   options:
#     max-size: "5m"
#     max-file: "2"

networks:
  default:
    # external: true
    name: otel-nginx

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
  collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./src/otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
  nginx:
    # image: nginx:alpine
    image: nginx-otel
    # container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      # - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./src/nginx/var/www/html:/var/www/html/
      - ./src/nginx/opentelemetry_module.conf:/etc/nginx/conf.d/opentelemetry_module.conf
    # logging: *logging