receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

exporters:
  logging:
  prometheusremotewrite:
    # endpoint: http://admin:admin@prometheus:9090/api/v1/write
    endpoint: http://prometheus:9090/api/v1/write
  prometheus:
    endpoint: 0.0.0.0:9090
    resource_to_telemetry_conversion:
      enabled: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheusremotewrite]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
