receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

exporters:
  logging:
  prometheusremotewrite:
    # endpoint: http://admin:admin@prometheus:9090/api/v1/write
    endpoint: http://prometheus:9090/api/v1/write
  prometheus:
    endpoint: 0.0.0.0:9090
    # startTime: "2023-02-07T00:00:08.979721+09:00"
    # endTime: "2023-02-08T00:00:01.048903+09:00"
    resource_to_telemetry_conversion:
      enabled: true

  influxdb:
    endpoint: http://localhost:8086
    timeout: 500ms
    org: shibly
    bucket: test
    token: OL3ddWoK1QESkRi-Hamycwc8JL8oj3gihVOr1blyOi2_wzhoAHnjmOPoYA__zrVJalz3_rorRRP_lnCGPMMENw==
    metrics_schema: telegraf-prometheus-v2

    sending_queue:
      enabled: true
      num_consumers: 3
      queue_size: 10

    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_interval: 3s
      max_elapsed_time: 10s

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheusremotewrite, influxdb]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
